version: "3"
services:
  client:
    build: ./client
    ports:
      - "3005:80"
    container_name: app-client
  api:
    build: ./server
    ports:
      - "5320:5320"
    depends_on:
      - db
    container_name: app-server
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: app-db